version: '3'
services:
  php:
    image: php:8.1.9-fpm
    volumes:
      - '../app:/symfony'

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - '../app:/symfony'
      - './nginx/conf.d:/etc/nginx/conf.d'
      
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306'
    volumes:
      - './volume/mysql:/var/lib/mysql'
